### ISSUE TITLE
Missing Poverty Data from Specific Countries

### ISSUE THREAD

**Issue by Aurorum** [owid/poverty-data#12]
Hiya, thanks so much for the great spreadsheet. Out of interest, is there any reason why Afghanistan doesn't seem to have been included in the dataset? A couple of other countries such as Bahrain appear to be missing too, but I couldn't find anything in the `README` to highlight which countries are missing or whether that's intentional and there's no data for them.

**Comment by paarriagadap** [comment]
Hello @Aurorum, thank you for your interest in the dataset. If you can't find a country in the here it is only because there is no data for it in the original source. You can check that at this link https://pip.worldbank.org/data-source. It is most likely that there are no suitable household income or consumption surveys available.

**Comment by Aurorum** [comment]
Thanks for your quick reply @paarriagadap! I'm still a little confused because the graph here shows a figure - https://ourworldindata.org/grapher/share-of-population-living-in-poverty-by-national-poverty-lines?tab=chart&country=AFG

But that figure doesn't seem to be included in the table. Is there a version of the dataset which includes all that data which is available, such as the above 54.5% figure shown in the graph? Might totally be misunderstanding what I'm looking at though. :)

Thanks again!!

**Comment by paarriagadap** [comment]
Ah, that chart shows poverty measured by national poverty lines, so each country defines which income level represents to be poor. This is a different approach: with the poverty data from national poverty lines the data by country is not easily comparable, but with international poverty lines it is possible.

We need to update the dataset of this repo in the future, and the data on that chart could be a candidate to be included.

For now, you can download the data by going to that chart, clinking on the Download button and selecting Full data (CSV) at the bottom.
<img width="561" alt="image" src="https://github.com/owid/poverty-data/assets/63430031/1a650b67-9d29-4d26-9606-28661ba3110f">

**Comment by Aurorum** [comment]
Got it - thanks so much for your help! Really appreciate it.
